{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 10,
   "id": "94e8b7ff",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception in thread Exception in thread Thread-220Thread-223Exception in thread Exception in thread Thread-231:\n",
      ":\n",
      "Traceback (most recent call last):\n",
      "Exception in thread Thread-233Exception in thread :\n",
      "Thread-232Exception in thread :\n",
      "Exception in thread Thread-234  File \"/Users/mhamani/miniconda3/lib/python3.8/threading.py\", line 932, in _bootstrap_inner\n",
      "Exception in thread Thread-237:\n",
      "Traceback (most recent call last):\n",
      "Traceback (most recent call last):\n",
      "Thread-227Traceback (most recent call last):\n",
      "Exception in thread Thread-226  File \"/Users/mhamani/miniconda3/lib/python3.8/threading.py\", line 932, in _bootstrap_inner\n",
      "  File \"/Users/mhamani/miniconda3/lib/python3.8/threading.py\", line 932, in _bootstrap_inner\n",
      ":\n",
      ":\n",
      "Thread-236Traceback (most recent call last):\n",
      ":\n",
      "  File \"/Users/mhamani/miniconda3/lib/python3.8/threading.py\", line 932, in _bootstrap_inner\n",
      "Exception in thread Exception in thread Traceback (most recent call last):\n",
      "Exception in thread Thread-229Thread-228Exception in thread :\n",
      ":\n",
      "  File \"/Users/mhamani/miniconda3/lib/python3.8/threading.py\", line 932, in _bootstrap_inner\n",
      "Thread-240Traceback (most recent call last):\n",
      "  File \"/Users/mhamani/miniconda3/lib/python3.8/threading.py\", line 932, in _bootstrap_inner\n",
      "Thread-250Traceback (most recent call last):\n",
      "Traceback (most recent call last):\n",
      "Traceback (most recent call last):\n",
      "Exception in thread Exception in thread   File \"/Users/mhamani/miniconda3/lib/python3.8/threading.py\", line 932, in _bootstrap_inner\n",
      "  File \"/Users/mhamani/miniconda3/lib/python3.8/threading.py\", line 932, in _bootstrap_inner\n",
      "  File \"/Users/mhamani/miniconda3/lib/python3.8/threading.py\", line 932, in _bootstrap_inner\n",
      "Thread-249Exception in thread :\n",
      "Thread-243:\n",
      "Traceback (most recent call last):\n",
      "Traceback (most recent call last):\n",
      "Thread-251:\n",
      ":\n",
      "  File \"/Users/mhamani/miniconda3/lib/python3.8/threading.py\", line 932, in _bootstrap_inner\n",
      ":\n",
      "Exception in thread   File \"/Users/mhamani/miniconda3/lib/python3.8/threading.py\", line 932, in _bootstrap_inner\n",
      "Traceback (most recent call last):\n",
      "      File \"/Users/mhamani/miniconda3/lib/python3.8/threading.py\", line 932, in _bootstrap_inner\n",
      "Traceback (most recent call last):\n",
      "Thread-257Exception in thread         :\n",
      ":\n",
      "Exception in thread :\n",
      "self.run()    Traceback (most recent call last):\n",
      "Thread-230self.run()Thread-242Exception in thread self.run()    :\n",
      "Traceback (most recent call last):\n",
      "Thread-256Traceback (most recent call last):\n",
      "  File \"/Users/mhamani/miniconda3/lib/python3.8/threading.py\", line 932, in _bootstrap_inner\n",
      ":\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/mhamani/miniconda3/lib/python3.8/threading.py\", line 932, in _bootstrap_inner\n",
      "            \n",
      "self.run()  File \"/Users/mhamani/miniconda3/lib/python3.8/threading.py\", line 932, in _bootstrap_inner\n",
      "  File \"/Users/mhamani/miniconda3/lib/python3.8/threading.py\", line 870, in run\n",
      "self.run()\n",
      "\n",
      "Traceback (most recent call last):\n",
      "Exception in thread     \n",
      "Exception in thread   File \"/Users/mhamani/miniconda3/lib/python3.8/threading.py\", line 870, in run\n",
      "Thread-258      File \"/Users/mhamani/miniconda3/lib/python3.8/threading.py\", line 870, in run\n",
      "  File \"/Users/mhamani/miniconda3/lib/python3.8/threading.py\", line 870, in run\n",
      "self.run()self.run()Traceback (most recent call last):\n",
      ":\n",
      "\n",
      "Thread-252  File \"/Users/mhamani/miniconda3/lib/python3.8/threading.py\", line 932, in _bootstrap_inner\n",
      "  File \"/Users/mhamani/miniconda3/lib/python3.8/threading.py\", line 932, in _bootstrap_inner\n",
      "self.run()  File \"/Users/mhamani/miniconda3/lib/python3.8/threading.py\", line 932, in _bootstrap_inner\n",
      "\n",
      "\n",
      "      File \"/Users/mhamani/miniconda3/lib/python3.8/threading.py\", line 870, in run\n",
      "  File \"/Users/mhamani/miniconda3/lib/python3.8/threading.py\", line 932, in _bootstrap_inner\n",
      "self.run()\n",
      "  File \"/Users/mhamani/miniconda3/lib/python3.8/threading.py\", line 932, in _bootstrap_inner\n",
      "      File \"/Users/mhamani/miniconda3/lib/python3.8/threading.py\", line 870, in run\n",
      "self.run()  File \"/Users/mhamani/miniconda3/lib/python3.8/threading.py\", line 870, in run\n",
      "  File \"/Users/mhamani/miniconda3/lib/python3.8/threading.py\", line 870, in run\n",
      ":\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/mhamani/miniconda3/lib/python3.8/threading.py\", line 932, in _bootstrap_inner\n",
      "Traceback (most recent call last):\n",
      "        \n",
      "Exception in thread \n",
      "self.run()self.run()\n",
      "  File \"/Users/mhamani/miniconda3/lib/python3.8/threading.py\", line 870, in run\n",
      "        self.run()self._target(*self._args, **self._kwargs)\n",
      "  File \"/Users/mhamani/Desktop/network_project/class_eNodeB.py\", line 35, in l_sgw\n",
      "    Exception in thread \n",
      "self._target(*self._args, **self._kwargs)self.run()  File \"/Users/mhamani/miniconda3/lib/python3.8/threading.py\", line 870, in run\n",
      ":\n",
      "\n",
      "  File \"/Users/mhamani/miniconda3/lib/python3.8/threading.py\", line 932, in _bootstrap_inner\n",
      "        self.run()        \n",
      "        self.run()self._target(*self._args, **self._kwargs)Exception in thread Thread-260self.run()Thread-259  File \"/Users/mhamani/miniconda3/lib/python3.8/threading.py\", line 870, in run\n",
      "Thread-253Exception in thread \n",
      "  File \"/Users/mhamani/miniconda3/lib/python3.8/threading.py\", line 870, in run\n",
      "self._target(*self._args, **self._kwargs)  File \"/Users/mhamani/Desktop/network_project/class_sgw.py\", line 80, in l_enodb\n",
      "Traceback (most recent call last):\n",
      "\n",
      "\n",
      "  File \"/Users/mhamani/Desktop/network_project/class_sgw.py\", line 80, in l_enodb\n",
      "  File \"/Users/mhamani/Desktop/network_project/class_mme.py\", line 34, in l_enodb\n",
      "\n",
      "  File \"/Users/mhamani/miniconda3/lib/python3.8/threading.py\", line 870, in run\n",
      "  File \"/Users/mhamani/miniconda3/lib/python3.8/threading.py\", line 870, in run\n",
      "  File \"/Users/mhamani/miniconda3/lib/python3.8/threading.py\", line 870, in run\n",
      ":\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/mhamani/miniconda3/lib/python3.8/threading.py\", line 932, in _bootstrap_inner\n",
      "  File \"/Users/mhamani/miniconda3/lib/python3.8/threading.py\", line 932, in _bootstrap_inner\n",
      "Thread-244    :\n",
      "    self.run():\n",
      "self.run()    \n",
      "    \n",
      "  File \"/Users/mhamani/miniconda3/lib/python3.8/threading.py\", line 870, in run\n",
      "\n",
      "\n",
      "NameErrorException in thread   File \"/Users/mhamani/miniconda3/lib/python3.8/threading.py\", line 870, in run\n",
      ":\n",
      "self.run()    \n",
      "  File \"/Users/mhamani/miniconda3/lib/python3.8/threading.py\", line 870, in run\n",
      "Thread-245Traceback (most recent call last):\n",
      "Traceback (most recent call last):\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/mhamani/miniconda3/lib/python3.8/threading.py\", line 932, in _bootstrap_inner\n",
      "self._target(*self._args, **self._kwargs)        self._target(*self._args, **self._kwargs)self.run()self.run()  File \"/Users/mhamani/miniconda3/lib/python3.8/threading.py\", line 932, in _bootstrap_inner\n",
      "    : \n",
      "      File \"/Users/mhamani/miniconda3/lib/python3.8/threading.py\", line 932, in _bootstrap_inner\n",
      "\n",
      "self._target(*self._args, **self._kwargs)    :\n",
      "\n",
      "self._target(*self._args, **self._kwargs)\n",
      "  File \"/Users/mhamani/Desktop/network_project/class_mme.py\", line 34, in l_enodb\n",
      "  File \"/Users/mhamani/miniconda3/lib/python3.8/threading.py\", line 870, in run\n",
      "Traceback (most recent call last):\n",
      "Exception in thread self._target(*self._args, **self._kwargs)\n",
      "\n",
      "    name 'socket' is not defined    \n",
      "  File \"/Users/mhamani/Desktop/network_project/class_eNodeB.py\", line 35, in l_sgw\n",
      "Thread-246      File \"/Users/mhamani/Desktop/network_project/class_eNodeB.py\", line 100, in l_data\n",
      "\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "\n",
      "  File \"/Users/mhamani/Desktop/network_project/class_sgw.py\", line 80, in l_enodb\n",
      "  File \"/Users/mhamani/miniconda3/lib/python3.8/threading.py\", line 870, in run\n",
      "  File \"/Users/mhamani/miniconda3/lib/python3.8/threading.py\", line 932, in _bootstrap_inner\n",
      "        self._target(*self._args, **self._kwargs)self._target(*self._args, **self._kwargs)    self._target(*self._args, **self._kwargs)      File \"/Users/mhamani/Desktop/network_project/class_eNodeB.py\", line 35, in l_sgw\n",
      "  File \"/Users/mhamani/Desktop/network_project/class_eNodeB.py\", line 158, in send\n",
      ":\n",
      "  File \"/Users/mhamani/miniconda3/lib/python3.8/threading.py\", line 870, in run\n",
      "self.run()\n",
      "  File \"/Users/mhamani/miniconda3/lib/python3.8/threading.py\", line 870, in run\n",
      "  File \"/Users/mhamani/miniconda3/lib/python3.8/threading.py\", line 870, in run\n",
      "\n",
      "\n",
      "\n",
      "  File \"/Users/mhamani/Desktop/network_project/class_sgw.py\", line 40, in l_mme\n",
      "  File \"/Users/mhamani/Desktop/network_project/class_mme.py\", line 34, in l_enodb\n",
      "Traceback (most recent call last):\n",
      "    self.run()        \n",
      "self.enb_p=[i+7000 for i in self.enbs]\n",
      "NameError: name 'socket' is not defined\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "\n",
      "        self._target(*self._args, **self._kwargs)\n",
      "  File \"/Users/mhamani/Desktop/network_project/class_eNodeB.py\", line 158, in send\n",
      "self._target(*self._args, **self._kwargs)  File \"/Users/mhamani/Desktop/network_project/class_eNodeB.py\", line 129, in l_sig\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "self._target(*self._args, **self._kwargs)          File \"/Users/mhamani/miniconda3/lib/python3.8/threading.py\", line 870, in run\n",
      "\n",
      "  File \"/Users/mhamani/miniconda3/lib/python3.8/threading.py\", line 932, in _bootstrap_inner\n",
      "self._target(*self._args, **self._kwargs)\n",
      "  File \"/Users/mhamani/Desktop/network_project/class_sgw.py\", line 80, in l_enodb\n",
      "  File \"/Users/mhamani/Desktop/network_project/class_eNodeB.py\", line 158, in send\n",
      "    self.run()\n",
      "  File \"/Users/mhamani/miniconda3/lib/python3.8/threading.py\", line 870, in run\n",
      "    \n",
      "NameError: name 'socket' is not defined\n",
      "NameError\n",
      "    self._target(*self._args, **self._kwargs)self._target(*self._args, **self._kwargs)    def l_sig(self):        \n",
      "self.run()\n",
      "  File \"/Users/mhamani/miniconda3/lib/python3.8/threading.py\", line 870, in run\n",
      ":   File \"/Users/mhamani/Desktop/network_project/class_eNodeB.py\", line 158, in send\n",
      "\n",
      "\n",
      "NameErrorname 'socket' is not defined  File \"/Users/mhamani/Desktop/network_project/class_eNodeB.py\", line 73, in l_mme\n",
      "\n",
      "  File \"/Users/mhamani/Desktop/network_project/class_eNodeB.py\", line 73, in l_mme\n",
      "\n",
      "    \n",
      "self.enb_p=[i+7000 for i in self.enbs]\n",
      "NameError: name 'socket' is not defined\n",
      "self.run()Exception in thread :         NameErrorThread-265    Exception in thread         data={}Exception in thread   File \"/Users/mhamani/Desktop/network_project/class_mme.py\", line 34, in l_enodb\n",
      "Exception in thread data={}\n",
      "NameError    Thread-271    \n",
      "NameError: \n",
      "\n",
      "    Thread-267: :\n",
      "    Traceback (most recent call last):\n",
      "    name 'socket' is not definedself._target(*self._args, **self._kwargs)\n",
      "  File \"/Users/mhamani/Desktop/network_project/class_eNodeB.py\", line 73, in l_mme\n",
      ":\n",
      "Thread-269NameError    : name 'socket' is not definedself._target(*self._args, **self._kwargs):\n",
      "self._target(*self._args, **self._kwargs)\n",
      "name 'socket' is not defined\n",
      ":   File \"/Users/mhamani/miniconda3/lib/python3.8/threading.py\", line 932, in _bootstrap_inner\n",
      "    :\n",
      "self._target(*self._args, **self._kwargs)data={}\n",
      "NameError: name 'pickle' is not defined\n",
      "name 'pickle' is not definedTraceback (most recent call last):\n",
      "Traceback (most recent call last):\n",
      "\n",
      "NameError\n",
      ": Traceback (most recent call last):\n",
      "  File \"/Users/mhamani/miniconda3/lib/python3.8/threading.py\", line 932, in _bootstrap_inner\n",
      "    self.run()NameErrorException in thread \n",
      "Thread-268:\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/mhamani/miniconda3/lib/python3.8/threading.py\", line 932, in _bootstrap_inner\n",
      "\n",
      "name 'socket' is not definedname 'socket' is not defined: name 'pickle' is not definedself.enb_p=[i+7000 for i in self.enbs]  File \"/Users/mhamani/miniconda3/lib/python3.8/threading.py\", line 870, in run\n",
      "\n",
      "Exception in thread   File \"/Users/mhamani/Desktop/network_project/class_eNodeB.py\", line 35, in l_sgw\n",
      "\n",
      "  File \"/Users/mhamani/Desktop/network_project/class_eNodeB.py\", line 100, in l_data\n",
      "Thread-272NameError    \n",
      "self.hfs=[]#handover ke omade ro befrestam jayi ke bayad\n",
      "    \n",
      ":\n",
      "  File \"/Users/mhamani/miniconda3/lib/python3.8/threading.py\", line 932, in _bootstrap_inner\n",
      "\n",
      "  File \"/Users/mhamani/Desktop/network_project/class_eNodeB.py\", line 73, in l_mme\n",
      "    \n",
      ": \n",
      "    NameError\n",
      "self._target(*self._args, **self._kwargs)\n",
      "  File \"/Users/mhamani/Desktop/network_project/class_eNodeB.py\", line 129, in l_sig\n",
      "NameError: name 'socket' is not defined\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/mhamani/miniconda3/lib/python3.8/threading.py\", line 932, in _bootstrap_inner\n",
      ":   File \"/Users/mhamani/miniconda3/lib/python3.8/threading.py\", line 932, in _bootstrap_inner\n",
      "    \n",
      "NameError    self.run()\n",
      "\n",
      "  File \"/Users/mhamani/miniconda3/lib/python3.8/threading.py\", line 870, in run\n",
      "name 'socket' is not defined\n",
      "NameError    : name 'socket' is not defined\n",
      "\n",
      "      File \"/Users/mhamani/miniconda3/lib/python3.8/threading.py\", line 870, in run\n",
      "data={}self._target(*self._args, **self._kwargs)\n",
      "NameError: name 'pickle' is not defined\n",
      "name 'socket' is not defined\n",
      "    self.run()\n",
      ": \n",
      "    NameError:     self.run()def l_sig(self):\n",
      "NameError: name 'socket' is not defined\n",
      "self.enb_p=[i+7000 for i in self.enbs]name 'socket' is not definedNameError    :             self._target(*self._args, **self._kwargs)self.run()name 'socket' is not defined\n",
      "\n",
      "\n",
      "self.run()\n",
      "\n",
      "    \n",
      "  File \"/Users/mhamani/miniconda3/lib/python3.8/threading.py\", line 870, in run\n",
      "  File \"/Users/mhamani/miniconda3/lib/python3.8/threading.py\", line 870, in run\n",
      "self._target(*self._args, **self._kwargs)    \n",
      "    NameError:   File \"/Users/mhamani/miniconda3/lib/python3.8/threading.py\", line 870, in run\n",
      "  File \"/Users/mhamani/Desktop/network_project/class_eNodeB.py\", line 129, in l_sig\n",
      "\n",
      "self.run()\n",
      "  File \"/Users/mhamani/Desktop/network_project/class_eNodeB.py\", line 129, in l_sig\n",
      "\n",
      "name 'socket' is not definedNameError: name 'socket' is not defined\n",
      "  File \"/Users/mhamani/miniconda3/lib/python3.8/threading.py\", line 870, in run\n",
      "\n",
      "\n",
      "name 'socket' is not defined  File \"/Users/mhamani/Desktop/network_project/class_eNodeB.py\", line 100, in l_data\n",
      "\n",
      "NameError    self._target(*self._args, **self._kwargs)"
     ]
    },
    {
     "ename": "IndexError",
     "evalue": "list index out of range",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mIndexError\u001b[0m                                Traceback (most recent call last)",
      "Input \u001b[0;32mIn [10]\u001b[0m, in \u001b[0;36m<cell line: 15>\u001b[0;34m()\u001b[0m\n\u001b[1;32m     13\u001b[0m network\u001b[38;5;241m.\u001b[39madd_user(\u001b[38;5;241m2\u001b[39m,[(\u001b[38;5;241m1\u001b[39m,\u001b[38;5;241m0\u001b[39m),(\u001b[38;5;241m0\u001b[39m,\u001b[38;5;241m1\u001b[39m),(\u001b[38;5;241m3\u001b[39m,\u001b[38;5;241m2\u001b[39m)],[\u001b[38;5;241m0.5\u001b[39m,\u001b[38;5;241m2\u001b[39m],[\u001b[38;5;241m0.1\u001b[39m,\u001b[38;5;241m0.7\u001b[39m,\u001b[38;5;241m0.3\u001b[39m,\u001b[38;5;241m0.4\u001b[39m])\n\u001b[1;32m     14\u001b[0m network\u001b[38;5;241m.\u001b[39mconnection_request(\u001b[38;5;241m0\u001b[39m,\u001b[38;5;241m1\u001b[39m,\u001b[38;5;124m'\u001b[39m\u001b[38;5;124m1.txt\u001b[39m\u001b[38;5;124m'\u001b[39m)\n\u001b[0;32m---> 15\u001b[0m \u001b[43mnetwork\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mconnection_request\u001b[49m\u001b[43m(\u001b[49m\u001b[38;5;241;43m2\u001b[39;49m\u001b[43m,\u001b[49m\u001b[38;5;241;43m3\u001b[39;49m\u001b[43m,\u001b[49m\u001b[38;5;124;43m'\u001b[39;49m\u001b[38;5;124;43m2.txt\u001b[39;49m\u001b[38;5;124;43m'\u001b[39;49m\u001b[43m)\u001b[49m\n\u001b[1;32m     17\u001b[0m network\u001b[38;5;241m.\u001b[39mrun()\n",
      "File \u001b[0;32m~/Desktop/network_project/class_network.py:56\u001b[0m, in \u001b[0;36mNetwork.connection_request\u001b[0;34m(self, sender_id, receiver_id, file_name)\u001b[0m\n\u001b[1;32m     53\u001b[0m k2\u001b[38;5;241m=\u001b[39m[(item[\u001b[38;5;241m0\u001b[39m],item[\u001b[38;5;241m1\u001b[39m],item[\u001b[38;5;241m2\u001b[39m],\u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39mn1) \u001b[38;5;28;01mfor\u001b[39;00m item \u001b[38;5;129;01min\u001b[39;00m \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39muser \u001b[38;5;28;01mif\u001b[39;00m receiver_id\u001b[38;5;241m==\u001b[39mitem[\u001b[38;5;241m0\u001b[39m]]\n\u001b[1;32m     55\u001b[0m s1\u001b[38;5;241m=\u001b[39muser_f(k1[\u001b[38;5;241m0\u001b[39m][\u001b[38;5;241m0\u001b[39m],k1[\u001b[38;5;241m0\u001b[39m][\u001b[38;5;241m1\u001b[39m],k1[\u001b[38;5;241m0\u001b[39m][\u001b[38;5;241m2\u001b[39m],k1[\u001b[38;5;241m0\u001b[39m][\u001b[38;5;241m3\u001b[39m],k1[\u001b[38;5;241m0\u001b[39m][\u001b[38;5;241m4\u001b[39m],k1[\u001b[38;5;241m0\u001b[39m][\u001b[38;5;241m5\u001b[39m],file_name)\n\u001b[0;32m---> 56\u001b[0m s2\u001b[38;5;241m=\u001b[39muser_g(\u001b[43mk2\u001b[49m\u001b[43m[\u001b[49m\u001b[38;5;241;43m0\u001b[39;49m\u001b[43m]\u001b[49m[\u001b[38;5;241m0\u001b[39m],k2[\u001b[38;5;241m0\u001b[39m][\u001b[38;5;241m1\u001b[39m],k2[\u001b[38;5;241m0\u001b[39m][\u001b[38;5;241m2\u001b[39m],k2[\u001b[38;5;241m0\u001b[39m][\u001b[38;5;241m3\u001b[39m])\n\u001b[1;32m     59\u001b[0m t1\u001b[38;5;241m=\u001b[39mthreading\u001b[38;5;241m.\u001b[39mThread(target\u001b[38;5;241m=\u001b[39ms1\u001b[38;5;241m.\u001b[39mrun1)\n\u001b[1;32m     60\u001b[0m t2\u001b[38;5;241m=\u001b[39mthreading\u001b[38;5;241m.\u001b[39mThread(target\u001b[38;5;241m=\u001b[39ms2\u001b[38;5;241m.\u001b[39mrun1)\n",
      "\u001b[0;31mIndexError\u001b[0m: list index out of range"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "\n",
      "\n",
      "  File \"/Users/mhamani/Desktop/network_project/class_users.py\", line 150, in send_loc1\n",
      ":     def l_sig(self):name 'socket' is not defined\n",
      "    self.run()    self._target(*self._args, **self._kwargs)NameError\n",
      "  File \"/Users/mhamani/miniconda3/lib/python3.8/threading.py\", line 870, in run\n",
      "\n",
      "  File \"/Users/mhamani/Desktop/network_project/class_eNodeB.py\", line 100, in l_data\n",
      ":       File \"/Users/mhamani/miniconda3/lib/python3.8/threading.py\", line 870, in run\n",
      "\n",
      "        name 'socket' is not defined    self._target(*self._args, **self._kwargs)    self._target(*self._args, **self._kwargs)\n",
      "\n",
      "self._target(*self._args, **self._kwargs)data={};\n",
      "  File \"/Users/mhamani/Desktop/network_project/class_users.py\", line 256, in l_sig\n",
      "NameError\n",
      ": \n",
      "  File \"/Users/mhamani/Desktop/network_project/class_users.py\", line 381, in send_loc1\n",
      "  File \"/Users/mhamani/Desktop/network_project/class_users.py\", line 68, in l_data\n",
      "name 'pickle' is not defined\n",
      "        self._target(*self._args, **self._kwargs)self._target(*self._args, **self._kwargs)\n",
      "        \n",
      "NameError: \n",
      "  File \"/Users/mhamani/Desktop/network_project/class_users.py\", line 295, in l_data\n",
      "name 'socket' is not defineddef l_sig(self):\n",
      "  File \"/Users/mhamani/Desktop/network_project/class_users.py\", line 30, in l_sig\n",
      "\n",
      "NameError\n",
      ": NameError: name 'socket' is not defined\n",
      "    name 'socket' is not defined    \n",
      "    return\n",
      "\n",
      "NameError: name 'socket' is not defined\n",
      "\n",
      "NameError: NameError        \n",
      "self.p_data=[i+6000 for i in self.enodbs]NameError: name 'time' is not defined\n",
      "name 'socket' is not defined: name 'socket' is not defined\n",
      "\n",
      "NameError: name 'socket' is not defined\n",
      "\n",
      "IOStream.flush timed out\n",
      "IOStream.flush timed out\n",
      "IOStream.flush timed out\n",
      "IOStream.flush timed out\n",
      "IOStream.flush timed out\n",
      "IOStream.flush timed out\n",
      "IOStream.flush timed out\n",
      "IOStream.flush timed out\n",
      "IOStream.flush timed out\n",
      "IOStream.flush timed out\n",
      "IOStream.flush timed out\n",
      "IOStream.flush timed out\n",
      "IOStream.flush timed out\n",
      "IOStream.flush timed out\n",
      "IOStream.flush timed out\n",
      "IOStream.flush timed out\n",
      "IOStream.flush timed out\n",
      "IOStream.flush timed out\n",
      "IOStream.flush timed out\n",
      "IOStream.flush timed out\n",
      "IOStream.flush timed out\n",
      "IOStream.flush timed out\n",
      "IOStream.flush timed out\n",
      "IOStream.flush timed out\n",
      "IOStream.flush timed out\n",
      "IOStream.flush timed out\n",
      "IOStream.flush timed out\n",
      "IOStream.flush timed out\n",
      "IOStream.flush timed out\n",
      "IOStream.flush timed out\n",
      "IOStream.flush timed out\n",
      "IOStream.flush timed out\n"
     ]
    }
   ],
   "source": [
    "import threading\n",
    "import socket\n",
    "import time\n",
    "import pickle\n",
    "from class_network import *\n",
    "\n",
    "\n",
    "network = Network(4,2,[(1,1),(2,1),(1,2),(2,2)])\n",
    "network.init_network()\n",
    "\n",
    "network.add_user(0,[(0,0),(0,2)],[0.5],[0.1,0.8,0.5,0.5])\n",
    "network.add_user(1,[(3,0),(3,2)],[1],0)\n",
    "network.add_user(2,[(1,0),(0,1),(3,2)],[0.5,2],[0.1,0.7,0.3,0.4])\n",
    "network.connection_request(0,1,'1.txt')\n",
    "network.connection_request(2,3,'2.txt')\n",
    "\n",
    "network.run()\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 8,
   "id": "714aa39b",
   "metadata": {},
   "outputs": [],
   "source": [
    "from class_eNodeB import eNodeB\n",
    "cc = eNodeB(10, [0,1], 3)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 11,
   "id": "62e87ad6",
   "metadata": {},
   "outputs": [],
   "source": [
    "from class_mme import MME\n",
    "mmeee = MME(10, 10)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 12,
   "id": "cb1f0958",
   "metadata": {},
   "outputs": [],
   "source": [
    "from class_sgw import SGW\n",
    "sgww = SGW(10, 10)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 16,
   "id": "e8b84693",
   "metadata": {},
   "outputs": [],
   "source": [
    "from class_users import user_g, user_f\n",
    "usergg = user_g(10, [1,2,23,4,5], 2, 10)\n",
    "userff = user_f(10, [1,2,4,5,6], 2, 20, 10, 10, '1.txt')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "232323cf",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.8.11"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
